### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by gatomo-oficial** [Mishify/Husky#8]
# REPORTES DE BUGS
Buenas. Al parecer debes reportar un bug de algo. Usa esta plantilla para rellenar las preguntas. Tendrás que editarlo en el Markdown y si no tienes ni idea puedes ir a [StackEdit](https://stackedit.io/), copiar el texto en Markdown, editarlo allí, copiar el texto editado y pegarlo aquí.

### Primeros datos
 * Explicación sencilla: para q tengo q hacer esto? soy dev no uno cualquiera
 * "Nombre" del error: y yo q se
 ### Tipo del error
 Quita la X del lugar que no es
 
 * [x] Leve
 * [ ] Grave

### Descripción
* Describe con detalle el bug: te lo he dicho por md

### Pasos a seguir para llegar al bug
Cambia ese texto de relleno por el tuyo

 1. ya sabes como hacerlo

### Software
Rellena las características básicas de tu pc

 - Marca PC (si no hay no poner): Ya sabes q mi pc es una patata y ese no es el problema
#### CPU
Quita la X del incorrecto

 - [x] Intel Core/Celeron/...
 - [x] AMD Ryzen/...

#### RAM
Quita la X del incorrecto

 - [x] <2 GB
 - [x] 2-4 GB
 - [x] 4-8 GB
 - [x] 8-16 GB
 - [x] >16 GB

#### SO
Quita la X del incorrecto

 - [x] Windows XP/Vista/7/8/10
 - [x] MacOS X
 - [x] Linux Ubuntu/Debian/Linux Mint/...

#### DISCORD APP (no chrome)

 - Versión: no lo se
 - Complementos: 
 - Nº de Servers en los que te has unido (aprox): 
 - Bots de tu server: 
 
 ## Otro soporte de información (capturas, etc)
 * Escribe y pon imágenes aqui

**Comment by gatomo-oficial** [comment]
ves? ya está
la plantilla la hice yo

**Comment by Phamzito** [comment]
perfect

**Comment by gatomo-oficial** [comment]
voy a cerrar esta inutilidad
